name: Sync main to sandbox-production

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync main to production branch and increment version
        uses: livekit-examples/sandbox-deploy-action
        secrets: inherit
